import "./globals.css";
import { Toaster } from 'react-hot-toast';

import Layout from "@/app/layout/page";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "美甲记账",
  description: "Generated by neil",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="zh-CN">
      <body>
        <Layout >
          <Toaster />
          {children}
        </Layout>
      </body>
    </html>
  );
}